network/urls.py
from django.urls import path

from . import views

app_name = "network"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("post", views.post, name="post"),
    path("posts", views.posts, name="posts"),
    path("like", views.like, name="like"),
    path("follow", views.follow, name="follow"),
    path("stats", views.stats, name="stats"),
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

    def __str__(self):
        return f"{self.username}"


class Follower(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")
    following_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="followers")
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} following {self.following_user.username}"


class Post(models.Model):
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    timestamp = models.DateTimeField(auto_now_add=True)

    def serialize(self):
        return {
            "id": self.id,
            "content": self.content,
            "user": self.user.username,
            "likes": len(self.likes.all()),
            "timestamp": self.timestamp.strftime("%b %d %Y, %I:%M %p")
        }

    def __str__(self):
        return f"Post: {self.id} by {self.user.username}"


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="likes")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="likes")
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"Like: {self.id} by {self.user.username} on Post: {self.post.id}"

network/views.py
import json
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.core.paginator import Paginator

from .models import User, Follower, Post, Like


def index(request):
    return render(request, "network/index.html")


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        if request.user.id != None:
            return HttpResponseRedirect(reverse("network:index"))
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("network:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("network:index"))
    else:
        if request.user.id != None:
            return HttpResponseRedirect(reverse("network:index"))
        return render(request, "network/register.html")


@login_required(login_url="network:login")
def post(request):
    if request.method == "POST":
        data = json.loads(request.body)
        content = data.get("content")
        post = Post(content=content, user=request.user)
        post.save()
        return JsonResponse({"message": "Post created successfully."}, status=201)
    
    # Edit post
    if request.method == "PUT":
        data = json.loads(request.body)
        id = int(data.get("id"))
        content = data.get("content")
        post = Post.objects.get(pk=id)

        # Prevent user from editing another user's posts
        if request.user.id != post.user_id:
            return HttpResponseRedirect(reverse("network:index"))
        post.content = content
        post.save()
        return JsonResponse({"content": content}, status=200)
    else:
        return HttpResponseRedirect(reverse("network:index"))


def posts(request):
    if request.method != "POST":
        return HttpResponseRedirect(reverse("network:index"))
    data = json.loads(request.body)
    collection = data.get("collection")
    user = request.user
    serialized_posts = []

    if collection == "all-posts":
        posts = Post.objects.all().order_by("-timestamp") 
    elif collection == "following":
        followed_users = user.following.all()
        followed_user_id_list = []
        for followed_user in followed_users:
           followed_user_id_list.append(followed_user.following_user.id)
        posts = Post.objects.filter(user_id__in=followed_user_id_list).all().order_by("-timestamp")
    else:
        profile = User.objects.get(username=collection)
        posts = Post.objects.filter(user_id=profile.id).all().order_by("-timestamp")

    for post in posts:
        serialized_post = post.serialize()
        serialized_post["liked"] = False
        likes = post.likes.all()
        for like in likes:
            if user.id == like.user.id:
                serialized_post.update(liked=True)
                break
        serialized_posts.append(serialized_post)

    paginator = Paginator(serialized_posts, 10)
    page_number = data.get("page")
    page_object = paginator.get_page(page_number)
        
    return JsonResponse({"posts": page_object.object_list, "pages": paginator.num_pages}, safe=False)


@login_required(login_url="network:login")
def like(request):
    if request.method != "POST":
        return HttpResponseRedirect(reverse("network:index"))

    data = json.loads(request.body)
    post_id = data.get("id")
    user = request.user
    post = Post.objects.get(pk=int(post_id))

    # Unlike if liked already
    for like in post.likes.all():
        if user.id == like.user.id:
            like.delete()
            like_count = len(post.likes.all())
            return JsonResponse({"like_count": like_count, "liked": False})

    like = Like(post=post, user=user)
    like.save()

    like_count = len(post.likes.all())
    return JsonResponse({"like_count": like_count, "liked": True})


def stats(request):
    if request.method != "POST":
        return HttpResponseRedirect(reverse("network:index"))
    data = json.loads(request.body)
    username = data.get("username")

    user = User.objects.get(username=username)
    followers = len(user.followers.all())
    following = len(user.following.all())

    if request.user.username == username:
        return JsonResponse({"following": following, "followers": followers})

    # Check if following
    followed = False
    for follower in user.followers.all():
        if follower.user.id == request.user.id:
            followed = True
            break

    return JsonResponse({"following": following, "followers": followers, "followed": followed})
        

@login_required(login_url="network:login")
def follow(request):
    if request.method != "POST":
        return HttpResponseRedirect(reverse("network:index"))

    user = request.user
    data = json.loads(request.body)
    following_username = data.get("username")
    following_user = User.objects.get(username=following_username)

    if user == following_user:
        return HttpResponseRedirect(reverse("network:index"))

    # Unfollow if already following
    following = user.following.all()
    
    for followed_user in following:
        if followed_user.following_user.id == following_user.id:
            followed_user.delete()
            return JsonResponse({"following": False})

    follower = Follower(user=request.user, following_user=following_user)
    follower.save()

    return JsonResponse({"following": True})

network/templates/network/index.html
{% extends "network/layout.html" %}

{% block body %}

<!-- SPA implemented in index.js -->
<div id="all-posts-view"></div>
<div id="following-view"></div>
<div id="profile-view"></div>

{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'network/styles.css' %}" rel="stylesheet">
        <script src="https://kit.fontawesome.com/7fa29c6afd.js" crossorigin="anonymous"></script>
        <script src="{% static 'network/index.js' %}"></script>
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'network:index' %}">Network</a>
          
            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" id="my-profile-link" href="#"><strong>{{ user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" id="all-posts-link" href="{% url 'network:index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" id="following-link" href="#">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'network:register' %}">Register here.</a>

{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'network:login' %}">Log In here.</a>

{% endblock %}